Project_DIAM/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('forum/', include('forum.urls')),
    path('admin/', admin.site.urls),
]

forum/urls.py
from django.urls import include, path
from . import views

app_name = 'forum'
urlpatterns = [
    path("", views.index, name="index"), # pagina inicial/home
    path("about", views.about, name="about"), # pagina about

    path("login", views.loginView, name="loginView"), # pagina login / funcao login -> pagina index
    path("logout", views.logoutView, name="logoutView"), # funcao logout -> pagina index
    path("sign_up", views.sign_up, name="sign_up"), # pagina signup / funcao registar -> pagina login
    path("editar_perfil", views.editar_perfil, name='editar_perfil'), # pagina editar perfil / funcao editar perfil -> pagina perfil
    path("editar_foto_perfil", views.editar_foto_perfil, name='editar_foto_perfil'), # funcao editar foto -> pagina perfil

    path("profile", views.profile, name="profile"), # pagina perfil
    path("criar_questao", views.criar_questao, name="criar_questao"), # pagina criar questao / funcao criar questao -> pagina index
    path("pesquisa_questoes", views.pesquisa_questoes, name="pesquisa_questoes"), # funcao pesquisa questoes -> pagina lista questoes
    path("questoes_user", views.questoes_user, name="questoes_user"), # funcao questoes user -> pagina lista questoes

    path("<int:questao_id>/detalhe_questao", views.detalhe_questao, name='detalhe_questao'), # pagina detalhe questao
    path("<int:questao_id>/apagar_questao", views.apagar_questao, name='apagar_questao'), # funcao apagar questao
    path("<int:questao_id>/like_questao", views.like_questao, name='like_questao'), # funcao da like a questao

    # react
    path('api/questoes/', views.questoes_lista),
]

forum/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

class Utilizador(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    imageURL = models.CharField(max_length=100, default="")
    descricao = models.CharField(max_length=500,default="")
    numeroQuestoes = models.IntegerField(default=0)

# Create your models here.
class Questao(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    questao_titulo = models.CharField(max_length=100, default="")
    questao_descricao = models.CharField(max_length=500, default="")
    questao_data = models.DateTimeField('data da publicacao')
    tags = models.ManyToManyField('Tag', related_name='questao')
    numero_likes = models.IntegerField(default=0)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE, null=True)

class Resposta(models.Model):
    # se eliminar a questao elimina as respostas
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    resposta_texto = models.CharField(max_length=10000)
    resposta_data = models.DateTimeField('data da resposta')


class Tag(models.Model):
    tag_texto = models.CharField(max_length=30)

forum/views.py
from django.utils import timezone
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

# react
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework import status
from .serializers import *

from forum.models import Questao, Resposta, Like, Utilizador, Tag


def index(request):
    latest_list = Questao.objects.order_by('-questao_data')[:20]
    return render(request, 'index.html', {"list": latest_list})


def about(request):
    return render(request, 'about.html')


def loginView(request):
    # metodo que verifica se existe dados em POST ( objetivo: minimalizar duas funcoes para uma funcao )
    if request.method == 'POST':
        try:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('forum:index'))
            else:
                return render(request, 'login_form.html', {'error_message': 'Username/Password inválidos'})
        except(KeyError):
            return render(request, 'login_form.html', {'error_message': 'Erro'})
    else:
        return render(request, 'login_form.html', )


@login_required(login_url='/forum/login')
def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse('forum:loginView'))


def sign_up(request):
    if request.method == 'POST':
        try:
            firstname = request.POST['firstname']
            lastname = request.POST['lastname']
            username = request.POST['username']
            password = request.POST['password']
            email = request.POST['email']
            descricao = request.POST['descricao']
            try:
                if User.objects.filter(username=username).exists():
                    return render(request, "sign_up.html",
                                  {'error_message': 'Erro: Nome de usuário já está em uso'})
                if User.objects.filter(email=email).exists():
                    return render(request, "sign_up.html",
                                  {'error_message': 'Erro: Endereço de e-mail já está em uso'})

                user = User.objects.create_user(username, email, password, first_name=firstname, last_name=lastname)
                utilizador = Utilizador(user=user, imageURL="images/default.png", descricao=descricao)
                utilizador.save()
                return HttpResponseRedirect(reverse("forum:loginView"))
            except:
                return render(request, "sign_up.html", {"error_message": "Erro ao criar o User. Tente Novamente"})
        except(KeyError):
            return render(request, "sign_up.html", {"error_message": "Erro"})
    else:
        return render(request, "sign_up.html")


@login_required(login_url='/forum/login')
def editar_perfil(request):
    if request.method == 'POST':
        try:
            firstname = request.POST['firstname']
            lastname = request.POST['lastname']
            username = request.POST['username']
            email = request.POST['email']
            descricao = request.POST['descricao']

            if User.objects.exclude(pk=request.user.pk).filter(username=username).exists():
                return render(request, "editar_perfil.html", {'error_message': 'Erro: Nome de usuário já está em uso'})
            if User.objects.exclude(pk=request.user.pk).filter(email=email).exists():
                return render(request, "editar_perfil.html",
                              {'error_message': 'Erro: Endereço de e-mail já está em uso'})

            request.user.first_name = firstname
            request.user.last_name = lastname
            request.user.username = username
            request.user.email = email
            request.user.utilizador.descricao = descricao
            request.user.save()
            request.user.utilizador.save()
            return HttpResponseRedirect(reverse('forum:profile'))
        except KeyError:
            return render(request, "editar_perfil.html", {'error_message': 'Erro: Tentar novamente'})
    else:
        return render(request, "editar_perfil.html")

@login_required(login_url='/forum/login')
def editar_foto_perfil(request):
    if request.method == 'POST':
        try:
            myfile = request.FILES['foto']
            fs = FileSystemStorage()
            filename = fs.save("forum/static/fotos/" + request.user.username + ".png", myfile)
            request.user.utilizador.imageURL = filename[13:]
            request.user.utilizador.save()
            return HttpResponseRedirect(reverse('forum:profile'))
        except KeyError:
            return render(request, 'editar_foto_perfil.html', {'error_message':"Erro. Tente Novamente"})
    else:
        return render(request, 'editar_foto_perfil.html')


@login_required(login_url='/forum/login')
def profile(request):
    return render(request, 'profile.html')


@login_required(login_url='/forum/login')
def criar_questao(request):
    if request.method == 'POST':
        try:
            questao_titulo = request.POST['questaotitulo']
            questao_descricao = request.POST['questaodescricao']
            tags = request.POST['tags']
            questao = Questao.objects.create(questao_titulo=questao_titulo, questao_descricao=questao_descricao, questao_data=timezone.now(),
                                             user=request.user)
            for tag in tags.split():
                aux = Tag.objects.filter(tag_texto=tag)
                if aux:
                    aux[0].questao.add(questao)
                else:
                    new_tag = Tag.objects.create(tag_texto=tag)
                    new_tag.questao.add(questao)
            if not request.user.is_superuser:
                request.user.utilizador.numeroQuestoes += 1
                request.user.utilizador.save()
        except(KeyError):
            return render(request, 'criar_questao.html', {'error_message': "Erro"})
        return HttpResponseRedirect(reverse('forum:questoes_user'))
    else:
        return render(request, 'criar_questao.html')


def pesquisa_questoes(request):
    if request.method == 'POST':
        try:
            tags = request.POST['tags']
            if (tags != ""):
                list = get_questions_with_tags(tags)
                return render(request, 'lista_questoes.html', {"list": list})
            else:
                return HttpResponseRedirect(reverse("forum:index"))
        except(KeyError):
            return HttpResponseRedirect(reverse("forum:index"))
    else:
        return HttpResponseRedirect(reverse("forum:index"))


def get_questions_with_tags(tags):
    questoes = {}
    for tag in tags.split():
        aux = Tag.objects.filter(tag_texto=tag)
        if aux:
            lista_questoes_com_tag = aux[0].questao.all()
            for questao in lista_questoes_com_tag:
                if questao in questoes.keys():
                    questoes[questao] = questoes[questao] + 1
                else:
                    questoes[questao] = 1
    tamanho = min(20, len(questoes))
    questoes_ordenadas = sorted(questoes.keys(), key=lambda k: questoes[k], reverse=True)[:tamanho]
    return list(questoes_ordenadas)


@login_required(login_url='/forum/login')
def questoes_user(request):
    questoes = Questao.objects.filter(user=request.user)
    return render(request, 'lista_questoes.html', {'list': questoes})


def detalhe_questao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    like = isLiked(request, questao)
    if request.method == 'POST':
        if request.user.is_authenticated:
            try:
                resposta_texto = request.POST['resposta_texto']
                Resposta.objects.create(questao=questao, user=request.user, resposta_texto=resposta_texto,
                                    resposta_data=timezone.now())
            except(KeyError):
                list_respostas = Resposta.objects.filter(questao=questao)
                return render(request, "detalhe_questao.html", {'questao': questao, "list": list_respostas, "like":like, "erro_message": "Erro"})
            list_respostas = Resposta.objects.filter(questao=questao)
            return render(request, 'detalhe_questao.html', {'questao': questao, "list": list_respostas, "like":like})
        else:
            list_respostas = Resposta.objects.filter(questao=questao)
            return render(request, 'detalhe_questao.html', {'questao':questao, 'list':list_respostas, "like":like, 'error_message':"Login necessário"})
    else:
        list_respostas = Resposta.objects.filter(questao=questao)
        return render(request, 'detalhe_questao.html', {'questao': questao, "list": list_respostas,"like":like})

def isLiked(request,questao):
    if request.user.is_authenticated:
        try:
            Like.objects.get(questao=questao, user=request.user)
            return True
        except Like.DoesNotExist:
            return False
    else: return False

@login_required(login_url='/forum/login')
def apagar_questao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    user = questao.user
    questao.delete()
    user.utilizador.numeroQuestoes -= 1
    user.utilizador.save()
    return HttpResponseRedirect(reverse("forum:index"))


@login_required(login_url='/forum/login')
def like_questao(request, questao_id):
    questao = get_object_or_404(Questao, pk=questao_id)
    try:
        like = Like.objects.get(user=request.user, questao=questao)
        like.delete()

forum/templates/about.html
{% extends 'index.html' %}

{% block search_bar %}

{% endblock %}

{% block conteudo %}

    <div class="about_container">
        <div class="about_clarify_logo">
            <img src="../static/images/clarify_logo.png" alt="logo_image">
        </div>
        <div class="about_text_container">
            <p class="about_text">Bem-vindo ao Clarify, o fórum de programação que está aqui para ajudá-lo a esclarecer suas dúvidas e fornecer
                soluções para seus desafios de programação. Somos uma comunidade apaixonada por tecnologia, com o objetivo de
                fornecer um espaço onde desenvolvedores e entusiastas possam compartilhar conhecimentos, discutir ideias e
                encontrar soluções inovadoras.
                Em Clarify, acreditamos que o aprendizado é uma jornada constante e que a colaboração é a chave para o sucesso.
                Nossa equipe de moderadores e membros experientes está sempre disponível para ajudá-lo, independentemente do
                seu nível de experiência em programação.
                Nós nos esforçamos para criar um ambiente acolhedor e inclusivo, onde todos possam se sentir à vontade para
                compartilhar seus conhecimentos e aprender com os outros. Estamos comprometidos em fornecer o melhor suporte
                possível e ajudá-lo a alcançar seus objetivos de programação.
                Junte-se a nossa comunidade hoje e comece a explorar tudo o que o Clarify tem a oferecer!
            </p>
        </div>
    </div>

{% endblock %}

forum/templates/criar_questao.html
{% extends 'index.html' %}

{% block search_bar %}
{% endblock %}

{% block conteudo %}

    <div class="criarquestao_content">

        <h2>Criar Questão</h2>
        <form class="criarquestao_form" action="{% url 'forum:criar_questao' %}" method="post">
            {% csrf_token %}

            <input class="titulo" type="text" name="questaotitulo" placeholder="Título"/><br>

            <textarea placeholder="Descrição" id="description" name="questaodescricao" rows="15" cols="50"></textarea><br>


            <input placeholder="Etiqueta" type="text" id="tags" name="tags" required /><br>

            <button type="submit">Criar Questão</button>
        </form>

    </div>

{% endblock %}

forum/templates/detalhe_questao.html
{% extends 'index.html' %}

{% block conteudo %}

    <div class="detalhe_questao_content">
        <div class="info_questao">

            <h1>{{ questao.questao_titulo }} ({{ questao.numero_likes }} likes)</h1>
            <p>
                {{ questao.questao_descricao }}
            </p>
            <form action="{% url 'forum:like_questao' questao.id %}">



                {% if like %}

                    <button id="heart-button" class="fa fa-heart" style="color: red; font-size: 20px"></button>

                {% else %}

                    <button id="heart-button" class="far fa-heart" style="color: black; font-size: 20px"></button>

                {% endif %}

                {% if request.user.is_authenticated and request.user == questao.user or request.user.is_superuser %}
                    <button type="submit" class="apagar" formaction="{% url 'forum:apagar_questao' questao.id %}" class="apagar_questao">
                        Apagar
                    </button>
                {% endif %}
            </form>


        </div>


        <div class="lista_resposta">
            <label>Respostas</label>
            {% if list %}
                <ul>
                    {% for resposta in list %}
                        <li class="question">
                            {{ resposta.user.username }}: {{ resposta.resposta_texto }}
                        </li>
                    {% endfor %}
                </ul>
            {% else  %}
                Não há repostas!!!
            {% endif %}

        </div>

        <form class="detalhe_questao_form" action="{% url 'forum:detalhe_questao' questao.id %}" method="post">
            {% csrf_token %}



            <textarea placeholder="Resposta" class="text_area" type="text" name="resposta_texto" rows="5" cols="50" required></textarea><br>

            <button class="submeter" type="submit">Submeter Resposta</button>
        </form>

    </div>

{% endblock %}

forum/templates/editar_foto.html
{% extends 'index.html' %}

{% block search_bar %}

{% endblock %}

{% block conteudo %}

    <div class="editar_foto_conteudo">
        <form method="post" enctype="multipart/form-data" action="{% url "forum:editar_foto" %}">
        {% csrf_token %}
            <h2>Editar Foto</h2>
            <input type="file" name="foto" accept="image/*" />
            <button type="submit" >Editar Foto</button>
        </form>
    </div>
    </script>
{% endblock %}

forum/templates/editar_foto_perfil.html
{% extends 'index.html' %}

{% block search_bar %}

{% endblock %}

{% block conteudo %}

    <div class="editar_foto_conteudo">
        <form method="post" enctype="multipart/form-data" action="{% url "forum:editar_foto_perfil" %}">
        {% csrf_token %}
            <h2>Editar Foto</h2>
{#            <input type="file" name="foto" accept="image/*" />#}
            <label for="foto" class="file-upload">Choose file</label>
            <input type="file" id="foto" name="foto" accept="image/*" />
            <button type="submit" >Editar Foto</button>
        </form>
    </div>


{% endblock %}

forum/templates/editar_perfil.html
{% extends 'index.html' %}

{% block search_bar %}

{% endblock %}

{% block conteudo %}

    <div class="editar_perfil_conteudo">
        <form action="{% url 'forum:editar_perfil' %}" method="post">
            {% csrf_token %}
            <h2>Editar Perfil</h2>
            <input placeholder="Primeiro Nome" type="text" name="firstname" value="{{ request.user.first_name }}" required/>

            <input placeholder="Último Nome" type="text" name="lastname" value="{{ request.user.last_name }}" required />

            <input placeholder="Username" type="text" name="username" value="{{ request.user.username }}" required />

            <input placeholder="E-mail" type="email" name="email" value="{{ request.user.email }}" required/>

            <textarea placeholder="Descrição" name="descricao" rows="3" cols="50" required >
                {{ request.user.utilizador.descricao }}</textarea>
            <button type="submit">Editar Perfil</button>
        </form>
    </div>

{% endblock %}

forum/templates/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'style/style.css' %}" />

<!DOCTYPE html>

<html>
    <head>
      <title>Clarify</title>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    </head>

    {% block error_message %}
    {% if error_message %}
        <script>
            alert('{{ error_message }}');
        </script>
    {% endif %}
    {% endblock %}

    <body>
        {% block header %}
        <header>
            <nav>
                <a href="{% url 'forum:index' %}"><img src="{% static 'images/clarify_logo.png' %}" alt="Logo"></a>
                {% block search_bar %}
                    <form class="search-form" action="{% url 'forum:pesquisa_questoes' %}" method="post" >
                    {% csrf_token %}
                        <input type="text" name="tags" placeholder="Search Tags .." />
                        <input type="submit" value="🔍" />
                    </form>
                {% endblock %}
                <div class="button_nav_list">
                    <a href="{% url 'forum:about' %}"><button>About</button></a>
                    {% if user.is_authenticated%}
                    <a href="{% url 'forum:logoutView' %}"><button>Logout</button></a>
                    {% else %}
                    <a href="{% url 'forum:loginView' %}"><button>Login</button></a>
                    <a href="{% url 'forum:sign_up' %}"><button>Sign Up</button></a>
                    {% endif %}
                </div>
            </nav>
        </header>
        {% endblock %}

        {% block main %}
        <section>
            {% if request.user.is_authenticated %}
            <div class="nav-perfil">

                <div class="profile_picture">
                    {% if user.is_superuser %}
                        <img id="foto_perfil" src="{% static 'images/profile.jpg' %}" alt="Profile Picture">
                    {% else %}
                        <img id="foto_perfil" src="{% static user.utilizador.imageURL %}" alt="Profile Picture">
                    {% endif %}
                </div>
                {% if not request.user.is_superuser %}
                <h4>Questões Criadas: {{request.user.utilizador.numeroQuestoes}} / 10</h4>
                {% endif %}
                <ul class="button_list">
                    {% if not user.is_superuser %}
                        <li>
                            <a href="{% url 'forum:profile' %}" class="button">Perfil</a>
                        </li>
                        <li>
                            <a href="{% url 'forum:editar_perfil' %}" class="button">Editar Perfil</a>
                        </li>

                    {% endif %}
                    <li>
                        <a href="{% url 'forum:questoes_user' %}" class="button">Questões</a>
                    </li>
                    {% if request.user.is_superuser or request.user.utilizador.numeroQuestoes < 10 %}
                    <li>
                        <a href="{% url 'forum:criar_questao' %}" class="button">Criar Questão</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            {% endif %}
            <div class="main{% if not request.user.is_authenticated %} full-width{% endif %}">
                {% block conteudo %}
                <div class="index_content">
                    <div class="left">
                        <div class="texto_introducao">
                            <h2>"Connecting coders, clarifying code."</h2>
                            <p>Clarify is a forum for all things related to coding. With a community of
                                passionate coders, you can find resources on a wide range of programming
                                languages and frameworks. Collaborate, ask questions, and share your knowledge
                                with other developers. Join Clarify today and explore the exciting world of coding!</p>
                        </div>
                        <div class="lista_questoes_index">
                            {% if list %}
                            <ul>
                                {% for questao in list %}
                                <li class="question"><form><button type="submit" formaction="{% url 'forum:detalhe_questao' questao.id %}">
                                    {{ questao.questao_titulo }}</button></form></li>
                                {% endfor %}
                            </ul>
                            {% else  %}
                                Não há perguntas.
                            {% endif %}
                        </div>
                    </div>
                    <div class="right">
                        <img src="{% static 'images/model.png' %}" alt="">
                    </div>
                </div>
            {% endblock %}
            </div>
        </section>
        {% endblock %}

        {% block footer %}
        <footer>
            <p>1980 Dahlia St Denver, CO 80220, EUA</p>
            <p>39.747371, -104.931689</p>
            <div class="social-icons">
                <a href="https://www.facebook.com/"><i class="fab fa-facebook"></i></a>
                <a href="https://www.youtube.com/"><i class="fab fa-youtube"></i></a>
                <a href="https://twitter.com/"><i class="fab fa-twitter"></i></a>
                <a href="https://www.linkedin.com/"><i class="fab fa-linkedin"></i></a>
            </div>
        </footer>
        {% endblock %}

        {#java script#}
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="{% static 'script/functions.js' %}"></script>

    </body>

</html>

forum/templates/lista_questoes.html
{% extends 'index.html' %}

{% block conteudo %}

    <div class="lista_questoes_container">
        <div class="title_container"><h2>Resultado Pesquisa</h2></div>
        <div class="lista_questoes_user">
            {% if list %}
                <ul>
                    {% for questao in list %}
                        <li class="question_user">
                            <form><button type="submit" formaction="{% url 'forum:detalhe_questao' questao.id %}">
                                {{ questao.questao_titulo }}</button></form>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                Não existem questões!!!
            {% endif %}
        </div>
    </div>

{% endblock %}

forum/templates/sign_up.html
{% extends 'index.html' %}

{% block conteudo %}

    <div class="signup_content">
        <form action="{% url 'forum:sign_up' %}" method="post">
            {% csrf_token %}
            <h1 class="form_title">Sign Up</h1>
            <div class="control">

                <input type="text" placeholder="Primeiro Nome" name="firstname" required>
            </div>
            <div class="control">

                <input type="text" placeholder="Último Nome" name="lastname" required>
            </div>
            <div class="control">

                <textarea placeholder="Descrição" name="descricao" id="" cols="30" rows="3"></textarea>
            </div>
            <div class="control">

                <input type="text" placeholder="Username" name="username" required>
            </div>
            <div class="control">

                <input type="password" placeholder="Nova Password" name="password" required>
            </div>
            <div class="control">

                <input type="text" placeholder="Inserir Email" name="email" required>
            </div>
            <div class="control">
                <button type="submit" class="login_button">Sign Up</button>
            </div>
        </form>
    </div>

{% endblock %}

forum/templates/teste.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style/teste.css' %}" />
<!DOCTYPE html>
<html>
    <head>
      <title>Clarify</title>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    </head>

    <body>
        {% block header %}
        <header>
            <nav>
                <a href="{% url 'forum:index' %}"><img src="{% static 'images/clarify_logo.png' %}" alt="Logo"></a>
                {% block search_bar %}
                <input type="text" placeholder="Search">
                {% endblock %}
                <div class="button">
                    <a href="{% url 'forum:about' %}"><button>About</button></a>
                    {% if user.is_authenticated%}
                    <a href="{% url 'forum:logoutView' %}"><button>Logout</button></a>
                    {% else %}
                    <a href="{% url 'forum:loginView' %}"><button>Login</button></a>
                    <a href="{% url 'forum:sign_up' %}"><button>Sign Up</button></a>
                    {% endif %}
                </div>
            </nav>
        </header>
        {% endblock %}

        {% block main %}
        <div class="container">
        {% if request.user.is_authenticated %}
            <div class="nav-perfil">
                <div class="profile_picture">
                    <img src="{% static 'images/profile.jpg' %}" alt="Profile Picture">
                </div>
                {% if not request.user.is_superuser %}
                <h4>Número de Questoes criadas: {{request.user.utilizador.numeroQuestoes}}</h4>
                {% endif %}
                <ul class="button_list">
                    <li>
                        <a href="{% url 'forum:editar_perfil' %}" class="button">Editar Perfil</a>
                    </li>
                    <li>
                        <a href="{% url 'forum:questoes_user' %}" class="button">Questões</a>
                    </li>
                    <li>
                        <a href="{% url 'forum:criar_questao' %}" class="button">Criar Questão</a>
                    </li>
                </ul>
            </div>
        {% endif %}
            <div class="main{% if not request.user.is_authenticated %} full-width{% endif %}">
                {% block conteudo %}
                <div class="index_content">
                    <div class="left">
                        <h3>"Connecting coders, clarifying code."</h3>
                        <p>Clarify is a forum for all things related to coding. With a community of passionate coders, you can find resources on a wide range of programming languages and frameworks. Collaborate, ask questions, and share your knowledge with other developers. Join Clarify today and explore the exciting world of coding!</p>
                    </div>
                    <div class="right">
                        <img src="{% static 'images/model.png' %}" alt="">
                    </div>
                    <div class="list">
                        {% if list %}
                        <ul>
                            {% for questao in list %}
                            <li class="question"><a href="{% url 'forum:detalhe_questao' questao.id %}">{{ questao.questao_texto }}</a></li>
                            {% endfor %}
                        </ul>
                        {% else  %}
                        A lista está vazia
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endblock %}
        </div>
        {% endblock %}

        {% block footer %}
        <footer>
            <p>1980 Dahlia St Denver, CO 80220, EUA</p>
            <p>39.747371, -104.931689</p>
            <div class="social-icons">
                <a href="https://www.facebook.com/" ><i class="fab fa-facebook"></i></a>
                <a href="https://www.youtube.com/" ><i class="fab fa-youtube"></i></a>
                <a href="https://twitter.com/" ><i class="fab fa-twitter"></i></a>
                <a href="https://www.linkedin.com/" ><i class="fab fa-linkedin"></i></a>
            </div>
        </footer>
        {% endblock %}
    </body>
</html>